name: Deploy Frontend to EC2

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-front
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: desarrollo2-catalogos-front

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: desarrollo2-catalogos-front/package-lock.json

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build
        run: |
          npm run build
          if [ -d "dist" ]; then
            echo "BUILD_DIR=dist" >> $GITHUB_ENV
          elif [ -d "build" ]; then
            echo "BUILD_DIR=build" >> $GITHUB_ENV
          else
            echo "No dist/ or build/ directory found" && exit 1
          fi

      # ✅ Comprobación segura de secrets (sin mostrarlos en claro)
      - name: Debug secrets (masked)
        shell: bash
        working-directory: .
        run: |
          set -e
          # Los secrets siempre se enmascaran en logs por GitHub, pero evitamos imprimirlos en claro igual.
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "EC2_USER: ${{ secrets.EC2_USER }}"
          # Password: solo longitud y hash truncado para confirmar que llegó
          if [ -z "${{ secrets.EC2_SSH_PASSWORD }}" ]; then
            echo "ERROR: Missing secret EC2_SSH_PASSWORD" >&2
            exit 1
          fi
          LEN=$(printf "%s" "${{ secrets.EC2_SSH_PASSWORD }}" | wc -c | tr -d ' ')
          HASH=$(printf "%s" "${{ secrets.EC2_SSH_PASSWORD }}" | sha256sum | cut -c1-12)
          echo "EC2_SSH_PASSWORD length: ${LEN}"
          echo "EC2_SSH_PASSWORD sha256 (first 12): ${HASH}"

      - name: Copy static assets to EC2 (password auth)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}           # desarrollo2-catalogos.online
          username: ci
          password: ${{ secrets.EC2_SSH_PASSWORD }}
          source: "desarrollo2-catalogos-front/${{ env.BUILD_DIR }}/**"
          target: "/home/ubuntu/catalogo/frontend/dist"
          strip_components: 0
          overwrite: true
          rm: true
          timeout: 2m

      - name: Restart Caddy + verify files on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ci
          password: ${{ secrets.EC2_SSH_PASSWORD }}
          script: |
            set -e
            cd /home/ubuntu/catalogo
            sudo docker compose restart caddy
            echo "== /home/ubuntu/catalogo/frontend/dist =="
            ls -lah frontend/dist | head -n 50
            echo "== /srv/frontend inside caddy =="
            sudo docker compose exec -T caddy sh -lc 'ls -lah /srv/frontend | head -n 50'
